### ISSUE TITLE
Change in JDK build # in EXPORT

### ISSUE THREAD

**Issue by jbesw** [aws-samples/aws-serverless-security-workshop#15]
The current export under "Downloading the latest Java jdk" reads:

`export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.42.amzn1.x86_64/jre`

... however this causes the error "We cannot execute /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.42.amzn1.x86_64/jre/bin/java". The exports needs to be updated to:

`export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.43.amzn1.x86_64/jre`

**Comment by angelarw** [comment]
thank you! updated.
