### ISSUE TITLE
Update Dependency Check Tool

### ISSUE THREAD

**Issue by jbesw** [aws-samples/aws-serverless-security-workshop#16]
Under "Dependency vulnerability with OWASP Dependency Check" --> "Downloading the tool", update bullet #2 so the wget command reads:

`wget -O dependency-check-5.1.0-release.zip http://dl.bintray.com/jeremy-long/owasp/dependency-check-5.1.0-release.zip`

The existing version errors out with -  "[ERROR] The download was interrupted; unable to complete the update".

**Comment by angelarw** [comment]
thank you! fixed
