### ISSUE TITLE
Apply least privilege principals

### ISSUE THREAD

**Issue by 0xdabbad00** [aws-samples/aws-serverless-security-workshop#37]
The purpose of this workshop is to teach security concepts, but a quick skim shows a lambda being giving `cognito-idp:*` on `*` and `dynamodb:*` on `*`.  These should be trimmed up.

https://github.com/aws-samples/aws-serverless-security-workshop/blob/c949379173cb904afab84d6ac8c2aed613e0c31d/src/template.yaml#L52

**Comment by angelarw** [comment]
the design of the workshop was intentional to start with a rather common but insecurely set-up web app, and have the participant implement security measures. the sam template provided therefore does not follow security best practices, on purpose.

**Comment by 0xdabbad00** [comment]
@angelarw Can you point out which of the modules shows the student how to implement least privileges then?

Further, it is not at all clear that this repo is purposefully insecure.  If that is the goal then it is best practice to indicate that by starting the README with something like `WARNING: This repo is purposefully insecure.`

**Comment by angelarw** [comment]
The README currently says `However, this simple serverless application is not very secure, and we need your help to implement measures to protect this serverless API from attackers.`

I can make it more obvious and add language around other security best practices. it was originally written for a in-person workshop so the speaker would do some of the explanation on encouraging participant to find other security issues. I agree more can be explained in the README

**Comment by angelarw** [comment]
i updated the readme. thank you for your feedback.
